// Generado desde el diseño aprobado (Isomorph Sitio v2). Fuente única de todo el copy.
// No editar a mano sin reflejarlo en el diseño: el sitio y el artefacto deben decir lo mismo.

export type Lang = 'es' | 'en';

export const es = {
  navCta: 'Cuéntanos qué falla',
  nav: ['Servicios', 'Trabajo', 'Cómo trabajamos', 'Contacto'],
  heroTitle: 'Tu sistema no está roto. Está desconectado.',
  heroSupport: 'Ingeniería e IA aplicada. Diseñamos, integramos y operamos sistemas a la medida — con profundidad en telecomunicaciones y contact centers.',
  heroCta: 'Cuéntanos qué está fallando',
  heroEyebrow: 'INGENIERÍA E IA APLICADA · BOGOTÁ',
  areaTitle: 'NUESTRAS ÁREAS DE TRABAJO',
  areaNodes: 'TELECOMUNICACIONES|INTEGRACIÓN DE SISTEMAS|AGENTES DE IA|PRODUCTO A LA MEDIDA|QA Y BRECHAS',
  heroCaption: 'CAMPO DE FUERZA · EL CURSOR EMPUJA LA RED, EL SCROLL LA ORDENA',
  tesisLead: 'La mayoría de las empresas no necesita software nuevo.',
  tesis: 'Necesita que lo que ya tiene hable entre sí, que alguien mida qué está fallando, y que los procesos que hoy dependen de una persona repitiendo lo mismo pasen a correr solos. Eso es lo que hacemos: entramos, entendemos la operación, y construimos lo que falta con ingenieros senior que ya resolvieron ese problema antes.',
  capsLabel: 'QUÉ HACEMOS', capsTitle: 'Cinco frentes, un mismo equipo',
  caps: [
    { title: 'Telecomunicaciones y contact center', desc: 'Control de calidad de llamadas, servidores de prueba, integración de telefonía y agentes de IA conectados a la operación.', chips: ['CALIDAD DE LLAMADAS', 'SERVIDORES DE PRUEBA', 'AGENTES EN OPERACIÓN'], page: 'telecom' },
    { title: 'Integración de sistemas', desc: 'Conectamos lo que ya existe. Full-code cuando hace falta, no-code cuando es más rápido y se sostiene igual.', chips: ['ERP', 'CRM', 'TELEFONÍA', 'MENSAJERÍA'], page: 'servicios' },
    { title: 'Agentes de IA y sistemas autónomos', desc: 'Procesos que corren solos y saben cuándo escalar a una persona. Agentes de llamada a la medida, con precios claros e integración con tus sistemas.', chips: ['AGENTES DE LLAMADA', 'PIPELINE DE CONTENIDO', 'OUTREACH A ESCALA'], page: 'servicios' },
    { title: 'Producto a la medida', desc: 'Web y móvil, arquitectura desde cero, sin plantillas.', chips: ['MARKETPLACE NÁUTICO'], page: 'servicios' },
    { title: 'QA y análisis de brechas', desc: 'Pruebas y hallazgo de huecos en el producto, antes de que los encuentre tu cliente.', chips: ['PREDICCIÓN DE CONVERSIÓN EN BANCA'], page: 'servicios' }
  ],
  telLabel: 'DONDE TENEMOS MÁS PROFUNDIDAD', telTitle: 'Contact centers que se pueden medir',
  telBody: 'Un contact center genera miles de llamadas al día y casi ninguna se revisa. Trabajamos sobre esa capa: montamos el control de calidad, levantamos servidores de prueba para no tocar producción, integramos la telefonía con los sistemas que ya usa el negocio, y conectamos agentes de IA donde descargan trabajo real sin sacar a la persona del proceso.',
  telLink: 'Ver el servicio completo', casoInsignia: 'CASO INSIGNIA',
  flagTitle: 'Pruebas de carga para picos de llamadas',
  flagBody: 'Cuántos agentes simultáneos aguanta la operación antes de degradarse — medido contra la telefonía física y los proveedores locales reales, no contra un laboratorio.',
  flagPoints: ['Capacidad real de servidores medida, no estimada', 'Puntos críticos de uso y punto de equilibrio', 'Simulación por pico, con estimación reportada', 'Un agente le explica al equipo qué falló en cada prueba'],
  flagLink: 'VER EL CASO →',
  comoLabel: 'CÓMO TRABAJAMOS', comoTitle: 'No mandamos un equipo genérico',
  comoBody: 'Cada proyecto lo arma un ingeniero senior que ya trabajó ese problema. Entramos como equipo técnico embebido, no como proveedor externo: nos sentamos con tu gente, entendemos la operación real, y salimos cuando el sistema corre sin nosotros.',
  comoLink: 'Ver el método completo',
  cierreTitle: '¿Qué es lo que hoy no funciona?',
  cierreBody: 'Cuéntanos el problema en dos párrafos. Te respondemos con un diagnóstico, no con un catálogo.',
  cierreCta: 'Escríbenos',
  svLabel: 'SERVICIOS', svTitle: 'Cinco frentes, un mismo equipo',
  svLede: 'No vendemos horas ni cargos. Vendemos que el problema quede resuelto y que tu equipo pueda operarlo sin nosotros.',
  svBlocks: [
    { title: 'Telecomunicaciones y contact center', body: 'Montamos el control de calidad de las llamadas con criterios que define tu equipo, levantamos servidores de prueba que replican la operación sin tocar producción, e integramos la telefonía con el CRM, el ERP y los canales de mensajería. Sobre esa base conectamos agentes de IA en los puntos donde descargan trabajo real, siempre con escalamiento a una persona.', link: 'Ver servicio', page: 'telecom' },
    { title: 'Integración de sistemas', body: 'Conectamos lo que ya existe en vez de reemplazarlo. Mapeamos qué guarda cada sistema, dónde se duplica la información y dónde se pierde, y construimos la capa que los pone de acuerdo. Full-code cuando el volumen o el control lo exigen, no-code cuando es más rápido y se sostiene igual.', link: 'Ver servicio', page: 'servicios' },
    { title: 'Agentes de IA y sistemas autónomos', body: 'Procesos que corren solos y saben cuándo escalar a una persona. Definimos el límite de decisión antes de escribir código: qué puede resolver el agente, qué tiene que aprobar alguien, y qué queda registrado para poder auditarlo después. Entregamos la trazabilidad, no solo el resultado. Incluye agentes de llamada a la medida —guion, voz y escalamiento definidos con tu equipo—, con precios claros por minuto y por implementación, e integración con los sistemas que ya usás.', link: 'Ver servicio', page: 'servicios' },
    { title: 'Producto a la medida', body: 'Web y móvil con arquitectura desde cero. Modelo de datos, flujos críticos y prototipos que tu equipo puede tocar antes de que exista el producto. Sin plantillas y sin temas comprados: lo que se construye es lo que tu operación necesita.', link: 'Ver servicio', page: 'servicios' },
    { title: 'QA y análisis de brechas', body: 'Pruebas automatizadas desde el primer sprint y revisión de los huecos que el producto ya tiene: rutas sin cubrir, estados de error sin diseñar, datos que nadie valida. El objetivo es encontrarlos antes de que los encuentre tu cliente.', link: 'Ver servicio', page: 'servicios' }
  ],
  limLabel: 'LÍMITES', limTitle: 'Qué hacemos, con qué condición, y qué no',
  limYesLabel: 'QUÉ SÍ', limMaybeLabel: 'CON CONDICIÓN', limNoLabel: 'QUÉ NO',
  limYes: ['Arquitectura y desarrollo de punta a punta', 'Integración con sistemas que ya están en producción', 'Agentes de IA conectados a procesos reales, con escalamiento a humano', 'Control de calidad y pruebas antes de que el cliente encuentre el hueco', 'Acompañamiento hasta que tu equipo lo opere solo'],
  limMaybe: ['Trabajo sobre sistemas legados: primero diagnóstico, después alcance', 'Plazos agresivos: se puede, recortando alcance, no calidad', 'Integraciones con proveedores que no exponen API documentada', 'Soporte 24/7: se puede, se cotiza aparte y con acuerdo de niveles'],
  limNo: ['No entregamos plantillas ni sitios armados sobre temas comprados', 'No cotizamos sin entender la operación primero', 'No prometemos cifras de resultado antes de medir la línea base', 'No dejamos sistemas que solo nosotros podemos mantener'],
  backServicios: '← SERVICIOS', tcLabel: 'SERVICIO', tcTitle: 'Telecomunicaciones y contact center',
  tcP1Label: 'EL PROBLEMA', tcP2Label: 'CÓMO LO ABORDAMOS', tcP3Label: 'QUÉ ENTREGAMOS', tcP4Label: 'TRABAJO RELACIONADO',
  tcP1: 'Las llamadas son el canal donde más pasa y donde menos se mide. La calidad se evalúa con muestras chicas, las pruebas se hacen sobre producción porque no hay ambiente aparte, y cada sistema —telefonía, CRM, mensajería— guarda su propia versión de lo que pasó.',
  tcP2: 'Empezamos midiendo lo que ya ocurre antes de proponer nada. Levantamos un ambiente de pruebas que replique la operación, instrumentamos la telefonía para tener datos reales de calidad, y recién ahí definimos qué automatizar.',
  tcEntrega: ['Control de calidad de llamadas con criterios definidos con tu equipo', 'Servidores de prueba que replican la operación sin tocar producción', 'Integración de telefonía con CRM, ERP y canales de mensajería', 'Agentes de IA en los puntos donde descargan trabajo real, con escalamiento a persona', 'Tableros de operación con las métricas que tu equipo ya usa'],
  tcCaption: 'TRÁFICO MEDIDO · HOVER UN NODO PARA VER SU LATENCIA',
  tcLimLabel: 'LÍMITES DE ESTE SERVICIO',
  tcLim1: 'CON CONDICIÓN: si la central telefónica no expone API, primero evaluamos qué se puede instrumentar.',
  tcLim2: 'QUÉ NO: no reemplazamos al equipo de operación, lo instrumentamos.',
  tcCta: 'Cuéntanos cómo está armada tu operación',
  tcRel1: 'PRUEBAS DE CARGA PARA PICOS DE LLAMADAS →',
  tcRel2: 'AGENTE QUE EXPLICA LOS FALLOS DE CADA PRUEBA →',
  trLabel: 'TRABAJO', trTitle: 'Problemas que ya resolvimos',
  trLede: 'Cada caso empieza por lo que estaba roto, no por la tecnología que usamos.',
  filters: ['TODOS', 'TELECOM', 'INTEGRACIÓN', 'AGENTES', 'PRODUCTO', 'QA'],
  cases: [
    { key: 'telecom', title: 'Pruebas de carga para picos de llamadas', problem: 'Los picos se descubrían en producción, con clientes adentro.', tags: ['TELECOM', 'INTEGRACIÓN'], keys: ['telecom', 'integracion'], filter: 'telecom', caso: 'telecom' },
    { key: 'boaty', title: 'Marketplace náutico', problem: 'Reservar un bote dependía de llamadas y WhatsApp.', tags: ['PRODUCTO', 'INTEGRACIÓN'], keys: ['producto', 'integracion'], filter: 'producto', caso: 'boaty' },
    { key: 'contenido', title: 'Pipeline autónomo de contenido', problem: 'Publicar consistente exigía una persona dedicada.', tags: ['AGENTES'], keys: ['agentes'], filter: 'agentes', caso: 'contenido' },
    { key: 'outreach', title: 'Outreach personalizado a escala', problem: 'El correo masivo dejó de convertir.', tags: ['AGENTES', 'INTEGRACIÓN'], keys: ['agentes', 'integracion'], filter: 'agentes', caso: 'outreach' },
    { key: 'banca', title: 'Predicción de conversión en banca', problem: 'El banco llamaba a toda la base por igual.', tags: ['QA'], keys: ['qa'], filter: 'qa', caso: 'banca' }
  ],
  emptyMsg: 'AÚN NO HAY NADA ACÁ. ES HONESTO, NO UN ERROR.', emptyCta: 'Quitar filtros',
  backTrabajo: '← TRABAJO', casoLabel: 'CASO',
  casoProblema: 'PROBLEMA', casoRestriccion: 'RESTRICCIÓN', casoConstruimos: 'LO QUE CONSTRUIMOS', casoResultado: 'RESULTADO',
  casoResultadoNota: 'SI NO HAY CIFRA MEDIDA, ESTA SECCIÓN SE OMITE ENTERA.',
  casoCaps: 'CAPACIDADES INVOLUCRADAS',
  casos: {
    banca: { title: 'Predicción de conversión en banca',
      problema: 'El equipo comercial llamaba a toda la base con el mismo guion y la misma prioridad. El costo por contacto era igual para un cliente que iba a contratar y para uno que no.',
      restriccion: 'Solo datos históricos ya disponibles, sin comprar fuentes externas, y el resultado tenía que ser interpretable para que el equipo comercial confiara en él.',
      construimos: 'Un modelo de clasificación sobre el histórico de campañas, con las variables que más pesan expuestas de forma legible, y una salida priorizada que el equipo usa antes de marcar.',
      hasResult: true, resultado: '−25 %',
      resultadoDetalle: 'Un cuarto menos de llamadas para llegar al mismo resultado comercial.',
      caps: ['QA Y ANÁLISIS DE BRECHAS', 'INTEGRACIÓN DE SISTEMAS'] },
    boaty: { title: 'Marketplace náutico',
      problema: 'Reservar un bote dependía de llamadas, WhatsApp y disponibilidad que nadie tenía centralizada. El dueño de la flota no sabía qué estaba libre hasta preguntarlo.',
      restriccion: 'Tenía que funcionar para dos públicos opuestos en la misma plataforma: quien reserva desde el teléfono y quien administra la flota desde un escritorio.',
      construimos: 'Marketplace con reserva instantánea, app móvil para el usuario final, panel web de gestión de flota, y pagos con división automática entre plataforma y propietario.',
      hasResult: false, caps: ['PRODUCTO A LA MEDIDA', 'INTEGRACIÓN DE SISTEMAS'] },
    telecom: { title: 'Pruebas de carga para picos de llamadas',
      problema: 'Nadie sabía cuántos agentes de llamada simultáneos aguantaba la operación antes de degradarse. Los picos se descubrían en producción, con clientes adentro, y la telefonía física estaba conectada a proveedores locales sin una forma de medir dónde cedía primero: el servidor, el enlace o el proveedor.',
      restriccion: 'Había que probar contra la misma telefonía física y los mismos proveedores locales que usa la operación, sin tumbar el servicio ni contratar capacidad extra para el experimento. Y el resultado tenía que poder leerlo el equipo de operación, no solo un ingeniero de redes.',
      construimos: 'Un banco de pruebas que mide la capacidad real de los servidores, evalúa los puntos críticos de uso y encuentra el punto de equilibrio de la operación. Corre una simulación de distintos picos y reporta la estimación para cada uno, analiza los problemas que aparecen en la red y los convierte en accionables concretos. Encima va un agente que le explica al equipo, en lenguaje llano, qué falló en cada prueba y por qué.',
      hasResult: false, caps: ['TELECOMUNICACIONES Y CONTACT CENTER', 'INTEGRACIÓN DE SISTEMAS'] },
    contenido: { title: 'Pipeline autónomo de contenido',
      problema: 'Publicar de forma consistente exigía una persona dedicada. El contenido salía tarde, con criterios distintos cada semana, y nadie tenía registro de qué se había publicado ni por qué.',
      restriccion: 'La marca ya tenía una guía escrita y el resultado no podía alejarse de ella. Todo lo generado tenía que quedar revisable antes de publicarse, no después.',
      construimos: 'Un pipeline que lee la estrategia de marca, genera las piezas por formato, las deja en cola de revisión y publica en los canales conectados. Cada pieza queda con su registro de qué la originó.',
      hasResult: false, caps: ['AGENTES DE IA Y SISTEMAS AUTÓNOMOS', 'INTEGRACIÓN DE SISTEMAS'] },
    outreach: { title: 'Outreach personalizado a escala',
      problema: 'El correo masivo dejó de convertir. El mismo mensaje a toda la base bajaba la apertura y empujaba el dominio hacia spam.',
      restriccion: 'Nada de comprar bases nuevas: había que trabajar con los contactos que ya existían en el CRM, y cada envío tenía que poder justificarse ante el equipo comercial.',
      construimos: 'Un sistema que analiza cada contacto contra su historial e industria, redacta el mensaje uno a uno, y lo deja en revisión antes del envío. El equipo comercial aprueba, el sistema despacha y registra.',
      hasResult: false, caps: ['AGENTES DE IA Y SISTEMAS AUTÓNOMOS', 'INTEGRACIÓN DE SISTEMAS'] }
  },
  mtLabel: 'MÉTODO', mtTitle: 'Cuatro etapas, sin sorpresas a mitad de camino',
  phases: [
    { n: '01', title: 'Discovery', when: 'SEMANAS 1 Y 2', body: 'Entramos a la operación antes de proponer arquitectura. Mapeamos qué sistemas hay, dónde se pierde información y qué procesos dependen hoy de que una persona repita algo. Sale un documento de alcance con lo que se puede y lo que no.' },
    { n: '02', title: 'Design', when: 'SEMANAS 3 Y 4', body: 'Arquitectura, modelo de datos y prototipos que tu equipo puede tocar. Acá se discute y se cambia, que es más barato que cambiarlo construido.' },
    { n: '03', title: 'Build', when: 'SEMANAS 5 A 12', body: 'Sprints quincenales con demo en ambiente de pruebas al final de cada uno. Integración continua y pruebas automatizadas desde el primer sprint, no al final.' },
    { n: '04', title: 'Launch', when: 'SEMANA 13 EN ADELANTE', body: 'Despliegue, telemetría real, y traspaso a tu equipo. Documentamos para que puedan operarlo sin nosotros — ese es el criterio de que terminamos.' }
  ],
  embTitle: 'No mandamos un equipo genérico',
  emb1: 'El problema de la mayoría de agencias no es técnico, es de asignación: te asignan quien esté libre. Nosotros armamos el equipo alrededor del problema. Si es calidad de llamadas, entra alguien que ya montó control de calidad de llamadas.',
  emb2: 'Trabajamos embebidos: en tus canales, en tus reuniones de operación, con acceso a la gente que conoce el proceso. No es un extra, es la única forma de que el sistema refleje cómo trabajan de verdad.',
  emb3: 'Y salimos. El objetivo es que tu equipo opere el sistema, no que dependa de nosotros para cada cambio.',
  mtCaption: 'DOCUMENTOS TÉCNICOS · VISTA CENITAL',
  ntIndex: 'NOTAS', ntSoon: 'PRÓXIMAS NOTAS EN CAMINO',
  ntEyebrow: 'NOTA · [DATO: FECHA]',
  ntTitle: 'Por qué el púrpura marca lo que escribió el modelo',
  ntLede: 'Una decisión de color que existe por honestidad, no por adorno.',
  ntP1: 'Cuando una interfaz mezcla texto escrito por una persona con texto generado por un modelo, el usuario tiene que poder distinguirlos antes de leer. No después, no al hacer clic: antes.',
  ntP2: 'En nuestro sistema eso se resuelve con dos canales que no compiten con el resto de la interfaz. Todo lo que produjo el modelo va sobre un tinte lavanda con borde púrpura. Y todo lo que la máquina midió —duraciones, argumentos, resultados— va en tipografía monoespaciada, mientras que lo que escribió una persona va en la sans.',
  ntP3: 'El púrpura bonito no pasó el filtro de contraste: daba 2,86:1 sobre el tinte. Hubo que inventar un token aparte solo para el texto.',
  ntAgentLabel: 'GENERADO POR EL MODELO',
  ntAgentOut: 'contrast(#5e4eba, #f2f2f9) = 2.86:1  → FAIL\ncontrast(#4a3e9e, #f2f2f9) = 4.51:1  → PASS\nduración: 0,31 s',
  ntAgentNote: 'BLOQUE OPCIONAL. SOLO APARECE SI LA NOTA MUESTRA SALIDA REAL DE UN MODELO.',
  ctLabel: 'CONTACTO', ctTitle: 'Cuéntanos qué está fallando',
  ctFigure: 'TU NODO · MOVÉ EL CURSOR DENTRO DEL CUADRO',
  ctLede: 'No necesitamos un brief formal. Dos párrafos de qué no funciona hoy alcanzan para empezar.',
  fName: 'NOMBRE', fCompany: 'EMPRESA', fMail: 'CORREO', fMsg: 'QUÉ NECESITAS RESOLVER',
  fMsgHelp: 'Qué está fallando hoy, qué sistemas hay involucrados, y qué pasaría si no se arregla.',
  submit: 'Enviar mensaje', sending: 'Enviando',
  errMail: 'ESE CORREO NO TIENE ARROBA. LO REVISAMOS DOS VECES.',
  okDraft: 'ABRIMOS TU CLIENTE DE CORREO CON EL MENSAJE ARMADO. FALTA QUE LE DES ENVIAR.',
  errSend: 'NO PUDIMOS ENVIARLO. EL MENSAJE SIGUE ACÁ, INTENTÁ DE NUEVO.',
  okSent: 'RECIBIDO. RESPONDEMOS EN 24H HÁBILES, NO EN "PRONTO".',
  ctFoot: 'RESPONDEMOS EN 24 HORAS HÁBILES · BOGOTÁ, COLOMBIA · HELLO@ISOMORPH.LAT',
  statesLabel: 'ESTADOS DEL FORMULARIO — REVISIÓN',
  stRest: 'REPOSO', stFocus: 'FOCO', stErr: 'ERROR DE CAMPO', stSending: 'ENVIANDO · DURACIÓN REAL', stSent: 'ENVIADO', stFail: 'ERROR DE ENVÍO',
  e404: 'ESTA RUTA NO EXISTE. TAMPOCO EXISTÍA AYER.', e404Home: 'Ir al inicio', e404Sv: 'Ver servicios',
  footStatus: 'SISTEMAS: OPERATIVOS · CAFÉ: CRÍTICO',
  footSvc: 'SERVICIOS', footCo: 'EMPRESA', footContact: 'CONTACTO',
  footSvcItems: ['Telecomunicaciones', 'Integración de sistemas', 'Agentes de IA', 'Producto a la medida', 'QA y brechas'],
  footCoLabels: ['Trabajo', 'Cómo trabajamos', 'Marca', 'Contacto'],

  mcLabel: 'MARCA', mcTitle: 'La marca es una palabra y un dibujo. No los mezclamos.',
  mcLede: 'Isomorph se firma con su nombre. El motivo K5 —el dibujo que aparece cuando explicamos un sistema— es ornamento: acompaña, nunca reemplaza.',
  mcLogoTitle: 'El logotipo es tipográfico',
  mcLogoBody: 'Isomorph en Newsreader 600, tracking −0,022em. No hay símbolo que lo sustituya ni versión abreviada. Cuando el espacio no alcanza para la palabra completa, el espacio no alcanza para la marca.',
  mcLogoPrim: 'PRIMARIO · LOGOTIPO SOLO',
  mcLogoLock: 'PERMITIDO · CON ORNAMENTO K5',
  mcRules: [
    'ALTURA MÍNIMA DEL LOGOTIPO: 16 PX. POR DEBAJO DE ESO, USE SOLO TEXTO.',
    'ESPACIO LIBRE ALREDEDOR: LA ALTURA DE LA "I" EN LOS CUATRO LADOS.',
    'DOS VERSIONES ÚNICAS: TINTA #ECEAE5 SOBRE OSCURO, #141517 SOBRE CLARO.'
  ],
  mcK5Title: 'K5 es ornamento, no logo',
  mcK5Body: 'K5 es un trazo continuo: se dibuja sin levantar el lápiz y vuelve sobre sí mismo hasta cerrar. Es lo que pasa cuando alguien explica un sistema en una servilleta. Vive en fondos, portadas y figuras técnicas. Se puede girar, escalar y recortar; lo que no se puede es usarlo como firma.',
  mcK5Drag: 'ARRASTRA PARA GIRAR',
  mcK5Reset: 'Reiniciar',
  mcK5Note: 'LOS DOS TRAZOS AZULES SON EL ACENTO. SIEMPRE DOS, SIEMPRE #7BA9FF, SIEMPRE EN EL MISMO CRUCE.',
  mcTypeTitle: 'Tipografía y escala',
  mcTypeSerifUse: 'Títulos, cuerpo y todo lo que se lee corrido. Es la voz del sitio.',
  mcTypeMonoUse: 'Etiquetas, datos, duraciones y estados. Todo lo que el sistema reporta.',
  mcScDisplay: 'Título de página',
  mcScTitle: 'Título de sección',
  mcScSub: 'Subtítulo de tarjeta',
  mcScBody: 'Cuerpo de texto, hasta 68 caracteres por línea.',
  mcScLabel: 'ETIQUETA MONO',
  mcUseTitle: 'Usos correctos e incorrectos',
  mcOk: 'CORRECTO', mcNo: 'INCORRECTO',
  mcU1: 'Logotipo solo, en tinta, sobre fondo oscuro.',
  mcU2: 'K5 al 16 % de opacidad detrás del contenido.',
  mcU2Tag: 'SISTEMA',
  mcU3: 'Inversión sobre papel: tinta oscura sobre #ECEAE5.',
  mcU4: 'K5 solo, funcionando como firma. No es el logo.',
  mcU5: 'Logotipo estirado o condensado. Nunca se deforma.',
  mcU6: 'Logotipo en color de acento y K5 recoloreado.',
  mcVoiceTitle: 'Voz y tono',
  mcVoiceBody: 'Escribimos como hablamos en una reunión técnica: nombramos el problema antes de la solución, y no prometemos lo que no medimos.',
  mcSay: 'ESCRIBIMOS', mcSayNot: 'NO ESCRIBIMOS',
  mcVoice: [
    { yes: 'Tu sistema no está roto. Está desconectado.', no: 'Soluciones end-to-end que potencian tu negocio.' },
    { yes: 'Respondemos en 24 horas hábiles, no "pronto".', no: 'Nos pondremos en contacto a la brevedad.' },
    { yes: 'Cada caso empieza por lo que estaba roto.', no: 'Stack: Kubernetes, Kafka, LLMs de última generación.' },
    { yes: 'Aún no hay nada acá. Es honesto, no un error.', no: 'Próximamente: casos de éxito.' }
  ],
  mcVoiceRules: [
    'FRASES CORTAS. UN PUNTO ANTES DE UNA CONJUNCIÓN.',
    'SIN SUPERLATIVOS: NADA ES LÍDER, INNOVADOR NI DISRUPTIVO.',
    'UN DATO QUE NO PODEMOS SUSTENTAR SE MARCA PENDIENTE, NO SE ESTIMA.'
  ],
  mcDlTitle: 'Descargables',
  mcDlBody: 'El ornamento K5 en vectorial y en mapa de bits, con fondo transparente y el acento en su lugar.',
  mcDlSvg: 'K5 — SVG', mcDlPng: 'K5 — PNG 2048 px',
  mcDlNote: 'EL LOGOTIPO NO SE DESCARGA: SE COMPONE. NEWSREADER 600, TRACKING −0,022EM, TINTA #ECEAE5 O #141517.'
};

export const en: typeof es = {
  ...es,
  navCta: 'Tell us what is failing',
  nav: ['Services', 'Work', 'How we work', 'Contact'],
  heroTitle: 'Your system is not broken. It is disconnected.',
  heroSupport: 'Engineering and applied AI. We design, integrate and operate custom systems — with depth in telecommunications and contact centers.',
  heroCta: 'Tell us what is failing',
  heroEyebrow: 'ENGINEERING & APPLIED AI · BOGOTÁ',
  areaTitle: 'OUR AREAS OF WORK',
  areaNodes: 'TELECOMMUNICATIONS|SYSTEMS INTEGRATION|AI AGENTS|CUSTOM PRODUCT|QA AND GAPS',
  heroCaption: 'FORCE FIELD · THE CURSOR PUSHES THE NETWORK, SCROLL ORDERS IT',
  tesisLead: 'Most companies do not need new software.',
  tesis: 'They need what they already have to talk to each other, someone to measure what is failing, and the processes that today depend on a person repeating the same thing to start running on their own. That is what we do: we come in, we understand the operation, and we build what is missing with senior engineers who have solved that problem before.',
  capsLabel: 'WHAT WE DO', capsTitle: 'Five fronts, one team',
  caps: [
    { title: 'Telecommunications and contact center', desc: 'Call quality control, test servers, telephony integration and AI agents wired into the operation.', chips: ['CALL QUALITY', 'TEST SERVERS', 'AGENTS IN OPERATION'], page: 'telecom' },
    { title: 'Systems integration', desc: 'We connect what already exists. Full-code when it is needed, no-code when it is faster and holds up just as well.', chips: ['ERP', 'CRM', 'TELEPHONY', 'MESSAGING'], page: 'servicios' },
    { title: 'AI agents and autonomous systems', desc: 'Processes that run on their own and know when to escalate to a person. Custom call agents, clear pricing, and integration with your systems.', chips: ['CALL AGENTS', 'CONTENT PIPELINE', 'OUTREACH AT SCALE'], page: 'servicios' },
    { title: 'Custom product', desc: 'Web and mobile, architecture from scratch, no templates.', chips: ['NAUTICAL MARKETPLACE'], page: 'servicios' },
    { title: 'QA and gap analysis', desc: 'Testing and finding the holes in the product before your customer does.', chips: ['BANKING CONVERSION MODEL'], page: 'servicios' }
  ],
  telLabel: 'WHERE WE GO DEEPEST', telTitle: 'Contact centers you can measure',
  telBody: 'A contact center generates thousands of calls a day and almost none are reviewed. We work on that layer: we set up quality control, stand up test servers so production is never touched, integrate telephony with the systems the business already uses, and wire AI agents in where they take real work off the floor without removing the person from the process.',
  telLink: 'See the full service', casoInsignia: 'FLAGSHIP CASE',
  flagTitle: 'Load testing for call peaks',
  flagBody: 'How many simultaneous agents the operation holds before degrading — measured against the real physical telephony and local carriers, not against a lab.',
  flagPoints: ['Real server capacity measured, not estimated', 'Critical usage points and the break-even point', 'A simulation per peak, with a reported estimate', 'An agent explains to the team what failed in each test'],
  flagLink: 'SEE THE CASE →',
  comoLabel: 'HOW WE WORK', comoTitle: 'We do not send a generic team',
  comoBody: 'Each project is staffed by a senior engineer who has worked that problem before. We come in as an embedded technical team, not an outside vendor: we sit with your people, understand the real operation, and leave when the system runs without us.',
  comoLink: 'See the full method',
  cierreTitle: 'What is not working today?',
  cierreBody: 'Tell us the problem in two paragraphs. We answer with a diagnosis, not a catalogue.',
  cierreCta: 'Write to us',
  svLabel: 'SERVICES', svTitle: 'Five fronts, one team',
  svLede: 'We do not sell hours or job titles. We sell the problem being solved and your team being able to run it without us.',
  svBlocks: [
    { title: 'Telecommunications and contact center', body: 'We set up call quality control with criteria your team defines, stand up test servers that replicate the operation without touching production, and integrate telephony with CRM, ERP and messaging channels. On top of that we wire AI agents in where they take real work off the floor, always with escalation to a person.', link: 'See service', page: 'telecom' },
    { title: 'Systems integration', body: 'We connect what already exists instead of replacing it. We map what each system stores, where information is duplicated and where it is lost, and build the layer that makes them agree. Full-code when volume or control demand it, no-code when it is faster and holds up just as well.', link: 'See service', page: 'servicios' },
    { title: 'AI agents and autonomous systems', body: 'Processes that run on their own and know when to escalate. We define the decision boundary before writing code: what the agent can resolve, what a person must approve, and what gets logged so it can be audited later. We deliver the traceability, not just the result. This includes custom call agents — script, voice and escalation defined with your team — with clear per-minute and per-implementation pricing, and integration with the systems you already use.', link: 'See service', page: 'servicios' },
    { title: 'Custom product', body: 'Web and mobile with architecture from scratch. Data model, critical flows and prototypes your team can touch before the product exists. No templates and no purchased themes: what gets built is what your operation needs.', link: 'See service', page: 'servicios' },
    { title: 'QA and gap analysis', body: 'Automated tests from the first sprint and a review of the holes the product already has: uncovered paths, undesigned error states, data nobody validates. The goal is to find them before your customer does.', link: 'See service', page: 'servicios' }
  ],
  limLabel: 'LIMITS', limTitle: 'What we do, on what condition, and what we do not',
  limYesLabel: 'WHAT WE DO', limMaybeLabel: 'WITH CONDITIONS', limNoLabel: 'WHAT WE DO NOT',
  limYes: ['End-to-end architecture and development', 'Integration with systems already in production', 'AI agents wired into real processes, with human escalation', 'Quality control and testing before the customer finds the hole', 'Support until your team runs it alone'],
  limMaybe: ['Work on legacy systems: diagnosis first, scope second', 'Aggressive deadlines: possible by cutting scope, not quality', 'Integrations with vendors that expose no documented API', '24/7 support: possible, quoted separately and with an SLA'],
  limNo: ['We do not ship templates or sites built on purchased themes', 'We do not quote before understanding the operation', 'We do not promise result figures before measuring the baseline', 'We do not leave systems only we can maintain'],
  backServicios: '← SERVICES', tcLabel: 'SERVICE', tcTitle: 'Telecommunications and contact center',
  tcP1Label: 'THE PROBLEM', tcP2Label: 'HOW WE APPROACH IT', tcP3Label: 'WHAT WE DELIVER', tcP4Label: 'RELATED WORK',
  tcP1: 'Calls are the channel where the most happens and the least is measured. Quality is judged on small samples, testing runs against production because there is no separate environment, and every system — telephony, CRM, messaging — keeps its own version of what happened.',
  tcP2: 'We start by measuring what already happens before proposing anything. We stand up a test environment that mirrors the operation, instrument telephony for real quality data, and only then define what to automate.',
  tcEntrega: ['Call quality control with criteria defined with your team', 'Test servers that replicate the operation without touching production', 'Telephony integration with CRM, ERP and messaging channels', 'AI agents where they take real work off the floor, with human escalation', 'Operations dashboards with the metrics your team already uses'],
  tcCaption: 'MEASURED TRAFFIC · HOVER A NODE FOR ITS LATENCY',
  tcLimLabel: 'LIMITS OF THIS SERVICE',
  tcLim1: 'WITH CONDITIONS: if the PBX exposes no API, we first assess what can be instrumented.',
  tcLim2: 'WHAT WE DO NOT: we do not replace your operations team, we instrument it.',
  tcCta: 'Tell us how your operation is put together',
  tcRel1: 'LOAD TESTING FOR CALL PEAKS →',
  tcRel2: 'AGENT THAT EXPLAINS EACH TEST FAILURE →',
  trLabel: 'WORK', trTitle: 'Problems we have already solved',
  trLede: 'Every case starts with what was broken, not with the technology we used.',
  filters: ['ALL', 'TELECOM', 'INTEGRATION', 'AGENTS', 'PRODUCT', 'QA'],
  cases: [
    { key: 'telecom', title: 'Load testing for call peaks', problem: 'Peaks were discovered in production, with customers on the line.', tags: ['TELECOM', 'INTEGRATION'], keys: ['telecom', 'integracion'], filter: 'telecom', caso: 'telecom' },
    { key: 'boaty', title: 'Nautical marketplace', problem: 'Booking a boat depended on phone calls and WhatsApp.', tags: ['PRODUCT', 'INTEGRATION'], keys: ['producto', 'integracion'], filter: 'producto', caso: 'boaty' },
    { key: 'contenido', title: 'Autonomous content pipeline', problem: 'Publishing consistently required a dedicated person.', tags: ['AGENTS'], keys: ['agentes'], filter: 'agentes', caso: 'contenido' },
    { key: 'outreach', title: 'Personalized outreach at scale', problem: 'Mass email stopped converting.', tags: ['AGENTS', 'INTEGRATION'], keys: ['agentes', 'integracion'], filter: 'agentes', caso: 'outreach' },
    { key: 'banca', title: 'Banking conversion prediction', problem: 'The bank was calling the whole base the same way.', tags: ['QA'], keys: ['qa'], filter: 'qa', caso: 'banca' }
  ],
  emptyMsg: 'NOTHING HERE YET. THAT IS HONEST, NOT AN ERROR.', emptyCta: 'Clear filters',
  backTrabajo: '← WORK', casoLabel: 'CASE',
  casoProblema: 'PROBLEM', casoRestriccion: 'CONSTRAINT', casoConstruimos: 'WHAT WE BUILT', casoResultado: 'RESULT',
  casoResultadoNota: 'IF THERE IS NO MEASURED FIGURE, THIS SECTION IS OMITTED ENTIRELY.',
  casoCaps: 'CAPABILITIES INVOLVED',
  casos: {
    banca: { title: 'Banking conversion prediction',
      problema: 'The commercial team called the entire base with the same script and the same priority. Cost per contact was identical for a client who would sign and one who would not.',
      restriccion: 'Only historical data already available, no external sources purchased, and the output had to be interpretable so the commercial team would trust it.',
      construimos: 'A classification model over the campaign history, with the heaviest variables exposed legibly, and a prioritized output the team uses before dialing.',
      hasResult: true, resultado: '−25%',
      resultadoDetalle: 'A quarter fewer calls to reach the same commercial result.',
      caps: ['QA AND GAP ANALYSIS', 'SYSTEMS INTEGRATION'] },
    boaty: { title: 'Nautical marketplace',
      problema: 'Booking a boat depended on calls, WhatsApp and availability nobody kept centralized. The fleet owner did not know what was free until asking.',
      restriccion: 'It had to work for two opposite audiences on the same platform: the person booking from a phone and the person managing the fleet from a desktop.',
      construimos: 'A marketplace with instant booking, a mobile app for the end user, a web fleet management panel, and payments split automatically between platform and owner.',
      hasResult: false, caps: ['CUSTOM PRODUCT', 'SYSTEMS INTEGRATION'] },
    telecom: { title: 'Load testing for call peaks',
      problema: 'Nobody knew how many simultaneous call agents the operation could hold before degrading. Peaks were discovered in production, with customers on the line, and the physical telephony ran through local carriers with no way to measure what gave out first: the server, the link, or the carrier.',
      restriccion: 'Testing had to run against the same physical telephony and the same local carriers the operation uses, without taking the service down or buying extra capacity for the experiment. And the output had to be readable by the operations team, not only by a network engineer.',
      construimos: 'A test bench that measures real server capacity, evaluates the critical usage points and finds the operation\'s break-even point. It simulates different peaks and reports an estimate for each, analyzes the network problems that surface and turns them into concrete action items. On top sits an agent that explains to the team, in plain language, what failed in each test and why.',
      hasResult: false, caps: ['TELECOMMUNICATIONS AND CONTACT CENTER', 'SYSTEMS INTEGRATION'] },
    contenido: { title: 'Autonomous content pipeline',
      problema: 'Publishing consistently required a dedicated person. Content went out late, with different criteria each week, and nobody had a record of what had been published or why.',
      restriccion: 'The brand already had a written guide and the output could not drift from it. Everything generated had to be reviewable before publishing, not after.',
      construimos: 'A pipeline that reads the brand strategy, generates pieces per format, queues them for review and publishes to the connected channels. Each piece carries a record of what originated it.',
      hasResult: false, caps: ['AI AGENTS AND AUTONOMOUS SYSTEMS', 'SYSTEMS INTEGRATION'] },
    outreach: { title: 'Personalized outreach at scale',
      problema: 'Mass email stopped converting. The same message to the whole base drove open rates down and pushed the domain toward spam.',
      restriccion: 'No buying new lists: the work had to use contacts already in the CRM, and every send had to be justifiable to the commercial team.',
      construimos: 'A system that analyzes each contact against their history and industry, writes the message one to one, and holds it for review before sending. The commercial team approves, the system dispatches and logs.',
      hasResult: false, caps: ['AI AGENTS AND AUTONOMOUS SYSTEMS', 'SYSTEMS INTEGRATION'] }
  },
  mtLabel: 'METHOD', mtTitle: 'Four stages, no surprises halfway through',
  phases: [
    { n: '01', title: 'Discovery', when: 'WEEKS 1 AND 2', body: 'We enter the operation before proposing architecture. We map what systems exist, where information is lost, and which processes depend on a person repeating something. The output is a scope document with what can and cannot be done.' },
    { n: '02', title: 'Design', when: 'WEEKS 3 AND 4', body: 'Architecture, data model and prototypes your team can touch. This is where it gets argued and changed, which is cheaper than changing it once built.' },
    { n: '03', title: 'Build', when: 'WEEKS 5 TO 12', body: 'Two-week sprints with a demo in the test environment at the end of each. Continuous integration and automated tests from the first sprint, not at the end.' },
    { n: '04', title: 'Launch', when: 'WEEK 13 ONWARD', body: 'Deployment, real telemetry, and handover to your team. We document it so they can operate it without us — that is our definition of finished.' }
  ],
  embTitle: 'We do not send a generic team',
  emb1: 'Most agencies have an assignment problem, not a technical one: you get whoever is free. We build the team around the problem. If it is call quality, the person who already built call quality control comes in.',
  emb2: 'We work embedded: in your channels, in your operations meetings, with access to the people who know the process. It is not an extra, it is the only way the system reflects how you actually work.',
  emb3: 'And we leave. The goal is your team operating the system, not depending on us for every change.',
  mtCaption: 'TECHNICAL DOCUMENTS · OVERHEAD VIEW',
  ntIndex: 'NOTES', ntSoon: 'MORE NOTES ON THE WAY',
  ntEyebrow: 'NOTE · [DATO: DATE]',
  ntTitle: 'Why purple marks what the model wrote',
  ntLede: 'A color decision that exists for honesty, not ornament.',
  ntP1: 'When an interface mixes text written by a person with text generated by a model, the user has to be able to tell them apart before reading. Not after, not on click: before.',
  ntP2: 'In our system that is solved with two channels that do not compete with the rest of the interface. Everything the model produced sits on a lavender tint with a purple border. And everything the machine measured — durations, arguments, results — is set in monospace, while what a person wrote is set in the sans.',
  ntP3: 'The pretty purple did not pass the contrast gate: it measured 2.86:1 on the tint. A separate token had to be invented just for the text.',
  ntAgentLabel: 'GENERATED BY THE MODEL',
  ntAgentOut: 'contrast(#5e4eba, #f2f2f9) = 2.86:1  → FAIL\ncontrast(#4a3e9e, #f2f2f9) = 4.51:1  → PASS\nduration: 0.31 s',
  ntAgentNote: 'OPTIONAL BLOCK. ONLY APPEARS IF THE NOTE SHOWS REAL MODEL OUTPUT.',
  ctLabel: 'CONTACT', ctTitle: 'Tell us what is failing',
  ctFigure: 'YOUR NODE · MOVE THE CURSOR INSIDE THE FRAME',
  ctLede: 'We do not need a formal brief. Two paragraphs on what is not working today is enough to start.',
  fName: 'NAME', fCompany: 'COMPANY', fMail: 'EMAIL', fMsg: 'WHAT DO YOU NEED SOLVED',
  fMsgHelp: 'What is failing today, which systems are involved, and what happens if it is not fixed.',
  submit: 'Send message', sending: 'Sending',
  errMail: 'THAT EMAIL HAS NO AT SIGN. WE CHECKED TWICE.',
  okDraft: 'WE OPENED YOUR MAIL CLIENT WITH THE MESSAGE READY. YOU STILL HAVE TO HIT SEND.',
  errSend: 'WE COULD NOT SEND IT. THE MESSAGE IS STILL HERE, TRY AGAIN.',
  okSent: 'RECEIVED. WE REPLY WITHIN 24 BUSINESS HOURS, NOT "SOON".',
  ctFoot: 'WE REPLY WITHIN 24 BUSINESS HOURS · BOGOTÁ, COLOMBIA · HELLO@ISOMORPH.LAT',
  statesLabel: 'FORM STATES — REVIEW',
  stRest: 'REST', stFocus: 'FOCUS', stErr: 'FIELD ERROR', stSending: 'SENDING · REAL DURATION', stSent: 'SENT', stFail: 'SEND ERROR',
  e404: 'THIS ROUTE DOES NOT EXIST. IT DID NOT EXIST YESTERDAY EITHER.', e404Home: 'Go home', e404Sv: 'See services',
  footStatus: 'SYSTEMS: OPERATIONAL · COFFEE: CRITICAL',
  footSvc: 'SERVICES', footCo: 'COMPANY', footContact: 'CONTACT',
  footSvcItems: ['Telecommunications', 'Systems integration', 'AI agents', 'Custom product', 'QA and gaps'],
  footCoLabels: ['Work', 'How we work', 'Brand', 'Contact'],

  mcLabel: 'BRAND', mcTitle: 'The brand is a word and a drawing. We do not merge them.',
  mcLede: 'Isomorph signs with its name. The K5 motif — the drawing we make when explaining a system — is ornament: it accompanies, it never replaces.',
  mcLogoTitle: 'The logotype is typographic',
  mcLogoBody: 'Isomorph in Newsreader 600, tracking −0.022em. There is no symbol that substitutes it and no abbreviated version. When there is not room for the whole word, there is not room for the brand.',
  mcLogoPrim: 'PRIMARY · LOGOTYPE ALONE',
  mcLogoLock: 'ALLOWED · WITH K5 ORNAMENT',
  mcRules: [
    'MINIMUM LOGOTYPE HEIGHT: 16 PX. BELOW THAT, USE PLAIN TEXT.',
    'CLEAR SPACE: THE HEIGHT OF THE "I" ON ALL FOUR SIDES.',
    'TWO VERSIONS ONLY: INK #ECEAE5 ON DARK, #141517 ON LIGHT.'
  ],
  mcK5Title: 'K5 is ornament, not a logo',
  mcK5Body: 'K5 is one continuous stroke: drawn without lifting the pen, folding back on itself until it closes. It is what happens when someone explains a system on a napkin. It lives in backgrounds, covers and technical figures. It can be rotated, scaled and cropped; what it cannot be is a signature.',
  mcK5Drag: 'DRAG TO ROTATE',
  mcK5Reset: 'Reset',
  mcK5Note: 'THE TWO BLUE STROKES ARE THE ACCENT. ALWAYS TWO, ALWAYS #7BA9FF, ALWAYS AT THE SAME CROSSING.',
  mcTypeTitle: 'Type and scale',
  mcTypeSerifUse: 'Headings, body and everything read in flow. It is the voice of the site.',
  mcTypeMonoUse: 'Labels, data, durations and states. Everything the system reports.',
  mcScDisplay: 'Page title',
  mcScTitle: 'Section title',
  mcScSub: 'Card subtitle',
  mcScBody: 'Body copy, up to 68 characters per line.',
  mcScLabel: 'MONO LABEL',
  mcUseTitle: 'Correct and incorrect use',
  mcOk: 'CORRECT', mcNo: 'INCORRECT',
  mcU1: 'Logotype alone, in ink, on a dark background.',
  mcU2: 'K5 at 16% opacity behind the content.',
  mcU2Tag: 'SYSTEM',
  mcU3: 'Inverted on paper: dark ink on #ECEAE5.',
  mcU4: 'K5 alone, working as a signature. It is not the logo.',
  mcU5: 'Logotype stretched or condensed. It never distorts.',
  mcU6: 'Logotype in the accent color and K5 recolored.',
  mcVoiceTitle: 'Voice and tone',
  mcVoiceBody: 'We write the way we talk in a technical meeting: name the problem before the solution, and never promise what we do not measure.',
  mcSay: 'WE WRITE', mcSayNot: 'WE DO NOT WRITE',
  mcVoice: [
    { yes: 'Your system is not broken. It is disconnected.', no: 'End-to-end solutions that empower your business.' },
    { yes: 'We reply within 24 business hours, not "soon".', no: 'We will get back to you shortly.' },
    { yes: 'Every case starts with what was broken.', no: 'Stack: Kubernetes, Kafka, state-of-the-art LLMs.' },
    { yes: 'Nothing here yet. That is honest, not an error.', no: 'Coming soon: success stories.' }
  ],
  mcVoiceRules: [
    'SHORT SENTENCES. A PERIOD BEFORE A CONJUNCTION.',
    'NO SUPERLATIVES: NOTHING IS LEADING, INNOVATIVE OR DISRUPTIVE.',
    'A FIGURE WE CANNOT BACK IS MARKED PENDING, NOT ESTIMATED.'
  ],
  mcDlTitle: 'Downloads',
  mcDlBody: 'The K5 ornament in vector and bitmap, transparent background, accent in place.',
  mcDlSvg: 'K5 — SVG', mcDlPng: 'K5 — PNG 2048 px',
  mcDlNote: 'THE LOGOTYPE IS NOT DOWNLOADED: IT IS SET. NEWSREADER 600, TRACKING −0.022EM, INK #ECEAE5 OR #141517.'
};

export const dict = { es, en } as const;
export type Dict = typeof es;

export const getDict = (lang: Lang): Dict => (lang === 'en' ? en : es);

/** Rutas por idioma. Las claves son las mismas en los dos idiomas. */
export const routes = {
  es: {
    home: '/',
    servicios: '/servicios',
    telecom: '/servicios/telecomunicaciones',
    trabajo: '/trabajo',
    caso: (slug: string) => '/trabajo/' + slug,
    metodo: '/metodo',
    marca: '/marca',
    contacto: '/contacto',
  },
  en: {
    home: '/en',
    servicios: '/en/services',
    telecom: '/en/services/telecom',
    trabajo: '/en/work',
    caso: (slug: string) => '/en/work/' + slug,
    metodo: '/en/how-we-work',
    marca: '/en/brand',
    contacto: '/en/contact',
  },
} as const;

/** Slug público de cada caso, por idioma. La clave es la del objeto `casos`. */
export const casoSlugs = {
  es: {
    banca: 'prediccion-de-conversion-en-banca',
    boaty: 'marketplace-nautico',
    telecom: 'pruebas-de-carga-picos-de-llamadas',
    contenido: 'pipeline-autonomo-de-contenido',
    outreach: 'outreach-personalizado-a-escala',
  },
  en: {
    banca: 'banking-conversion-prediction',
    boaty: 'nautical-marketplace',
    telecom: 'load-testing-call-peaks',
    contenido: 'autonomous-content-pipeline',
    outreach: 'personalized-outreach-at-scale',
  },
} as const;

export type CasoKey = keyof typeof casoSlugs.es;

export const casoKeyFromSlug = (lang: Lang, slug: string): CasoKey | null => {
  const table = casoSlugs[lang];
  const hit = (Object.keys(table) as CasoKey[]).find((k) => table[k] === slug);
  return hit ?? null;
};
